name: Wiki
description: Inquiries specifically for the Wiki.
title: '[Wiki]: '
assignees:
  - skuqre
labels:
  - wiki
body:
  - type: markdown
    attributes:
      value: |
        Please add to the title above to include a brief statement that provides the gist of your Wiki inquiry.
  - type: textarea
    attributes:
      label: What's your inquiry?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Double-checking
      options:
        - label: >-
            I have changed the title to include a brief statement that provides the gist of the Wiki
            inquiry.
          required: true
        - label: >-
            I have looked around the Issues tab and have not seen any similar
            inquiries to this Wiki inquiry.
          required: true
